name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Streamlit image
      run: |
        docker build --no-cache -t basudevp/msrit-bank-risk-cat-streamlit:latest -f docker.streamlit .
        docker push basudevp/msrit-bank-risk-cat-streamlit:latest

    - name: Build and push FastAPI image
      run: |
        docker build --no-cache -t basudevp/msrit-bank-risk-cat-fastapi:latest -f docker.fastapi .
        docker push basudevp/msrit-bank-risk-cat-fastapi:latest
